# Author : Shyam Rathi

baseURL = "https://www.rathi.dev"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Shyam Rathi"
theme = "hugo-tranquilpeak-theme"

disqusShortname = "rathi-dev"
googleAnalytics = "UA-140822118-1"

paginate = 7
canonifyurls = true
enableRobotsTXT = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Shyam Rathi"
  bio = "A software engineer from the Silicon Valley, California."
  job = "Sr. Manager of Engineering at Nutanix, San Jose"
  location = "California, USA"
  # gravatarEmail = "shyam29@gmail.com"
  picture = "/images/profile_pic.jpg"
  # twitter = "thibaudlepretre"
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 10
  identifier = "post"
  name = "Posts"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-text-o\" title='Posts'></i>"
  url = "/post"
[[menu.main]]
  weight = 20
  identifier = "resume"
  name = "Resume"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-pdf-o\" title='Resume'></i>"
  url = "/docs/resume-shyamsunder-2022.pdf"
[[menu.main]]
  weight = 30
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 40
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 50
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"

[[menu.links]]
  weight = 10
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\" title='Home'></i>"
  url = "/"
[[menu.links]]
  weight = 20
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"
[[menu.links]]
  weight = 30
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/ssrathi"

[[menu.misc]]
  weight = 1
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  dateFormat = "02 Jan 2006"
  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["programming", "history", "blog"]

  syntaxHighlighter = "highlight.js"
  clearReading = false
  hierarchicalCategories = false
  description = "Shyam Rathi - Personal Website"
  sidebarBehavior = 2
  coverImage = "background.jpg"

  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  favicon = "/favicon.png"

  swapPaginator = true

  # [[params.customCSS]]
  #   href = "css/mystyle.css"
  # [[params.customJS]]
  #   src = "js/myscript.js"

  # Sharing options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"
